name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler:
          - gcc-11
          - gcc-10
          - gcc-9
          - gcc-8
          - gcc-7
          - clang-12
          - clang-11
          - clang-10
          - clang-9
          - clang-8
          - clang-7
        cpp_std:
          - 17
          - 20
    container:
      image: "registry.gitlab.com/offa/plug/ci/${{ matrix.compiler }}:latest"
    name: "${{ matrix.compiler }} (C++${{ matrix.cpp_std }})"
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          mkdir _build && cd _build
          cmake -DCMAKE_CXX_STANDARD=${{ matrix.cpp_std }} -DWERROR=ON ..
          make -j
